config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'stories#index'

  resources :stories, only: [:index] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story

  validates :story, :hacker_news_id, :author, :text, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :comments

  validates :title, :url, :hacker_news_id, presence: true
  validates :hacker_news_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    FetchHackerNewsJob.perform_later
    @stories = Story.all.limit(15)
  end

  def search
    @stories = Story.where("title ILIKE ?", "%#{params[:query]}%").limit(10).page(params[:page])
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hacker News Stories</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-4">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.5.1.slim.min.js' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>
  </body>
</html>

app/views/stories/index.html.erb
<h1 class="text-center mb-4">Top 15 Hacker News Stories</h1>

<div class="mb-4">
  <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

<%= form_with url: search_stories_path, method: :get, local: true do %>
  <div class="input-group mb-3">
    <%= text_field_tag :query, params[:query], placeholder: 'Procurar por...', class: 'form-control' %>
    <div class="input-group-append">
      <%= submit_tag 'Buscar', class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

<div class="list-group">
  <% @stories.each do |story| %>
    <div class="list-group-item">
      <h5><%= link_to story.title, story.url, target: '_blank' %></h5>

      <% if story.comments.any? %>
        <h6>Quantidade de comentários relevantes: <%= story.comments.count %></h6>
      <% else %>
        <p>Nenhum comentário relevante disponível.</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/stories/search.html.erb
<h1>Resultado da busca por '<%= @keyword %>'</h1>

<ul>
  <% @stories.each do |story| %>
    <li>
      <a href="<%= story['url'] %>"><%= story['title'] %></a>
    </li>
  <% end %>
</ul>

<div class="d-flex justify-content-center">
  <%= paginate @stories %>
</div>